services:
  code-interpreter:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-interpreter:latest
    container_name: code-interpreter
    restart: unless-stopped
    privileged: true
    command: /app/.venv/bin/fastapi run app/main.py --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - HOST_PATH=$PWD
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - .:/app/
      - venv:/app/.venv
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  venv:
